language: php
php: 5.5
  
script: phpunit --configuration test/configuration.xml
  
before_install:
  - composer install
  - mysql -e "GRANT ALL PRIVILEGES ON allergeeks.* TO 'allergeeks'@'localhost' IDENTIFIED BY ''" -uroot
  - mysql -uroot < test/schema.sql
  
branches:
  only:
    - register
