<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-02 at 11:53:17.
 */
class IngredientTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Ingredient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Ingredient::create("Testingredient");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ingredient::get_by_id
     */
    public function testGet_by_id() {
        $testing = Ingredient::get_by_id($this->object->get_id());

        $this->assertEquals($this->object->get_name(), $testing->get_name());
        $this->assertEquals($this->object->get_id(), $testing->get_id());
    }

    /**
     * @covers Ingredient::get_by_name
     */
    public function testGet_by_name() {
        $testing = Ingredient::get_by_name("Testingredient")[0];

        $this->assertEquals('Testingredient', $testing->get_name());
    }

    /**
     * @covers Ingredient::create
     */
    public function testCreate() {
        $testing_new = Ingredient::create("TestCreateIng");

        $testing = Ingredient::get_by_id($testing_new->get_id());

        $this->assertEquals($testing_new->get_name(), $testing->get_name());
        $this->assertEquals($testing_new->get_id(), $testing->get_id());
    }

    /**
     * @covers Ingredient::get_id
     * @todo   Implement testGet_id().
     */
    public function testGet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ingredient::get_name
     * @todo   Implement testGet_name().
     */
    public function testGet_name() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ingredient::set_name
     */
    public function testSet_name() {
        $this->object->set_name("NewTest");

        $testing = Ingredient::get_by_id($this->object->get_id());

        $this->assertEquals('NewTest', $testing->get_name());

        //revert changes
        $this->object->set_name("Testingredient");
    }

}
