<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-03 at 23:00:29.
 */
class SessionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Session
     */
    protected $email_session;
    protected $barcode_session;
    protected $token_session;
    
    public static function setUpBeforeClass() {
        @session_start();
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $this->email_session = Session::get_by_login('marco.heumann@web.de', 'password');
        $this->barcode_session = Session::get_by_barcode(7529844743929);
        $this->token_session = Session::get_by_token('adf437590bca5a7d678d');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Session::get_by_token
     * @todo   Implement testGet_by_token().
     */
    public function testGet_by_token() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Session::get_by_barcode
     * @todo   Implement testGet_by_barcode().
     */
    public function testGet_by_barcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Session::get_by_login
     * @todo   Implement testGet_by_login().
     */
    public function testGet_by_login() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

   /**
     * @covers Session::is_token
     */
    public function testIs_token() {
        $this->assertTrue(Session::is_token('a6888afedc443b4adf70'));
    }

    /**
     * @covers Session::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Session::generate_barcode
     */
    public function testGenerate_barcode() {
        $barcode = Session::generate_barcode();

        $this->assertTrue(is_numeric($barcode));
        $this->assertEquals(13, strlen($barcode));
    }

    /**
     * @covers Session::get_user
     * @todo   Implement testGet_user().
     */
    public function testGet_user() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Session::get_token
     * @todo   Implement testGet_token().
     */
    public function testGet_token() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Session::is_admin
     * @todo   maybe also need to test an admin token
     */
    public function testIs_admin() {
        $this->assertTrue($this->email_session->is_admin());
        $this->assertFalse($this->barcode_session->is_admin());
        $this->assertFalse($this->token_session->is_admin());
    }

    /**
     * @covers Session::to_json
     * @todo   Implement testTo_json().
     */
    public function testTo_json() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Session::get_all_sessions
     * @todo   Implement testGet_all_sessions().
     */
    public function testGet_all_sessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
