<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-02 at 11:13:13.
 */
class UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User('');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers User::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::get_by_id
     * @todo   Implement testGet_by_id().
     */
    public function testGet_by_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::get_by_email
     * @todo   Implement testGet_by_email().
     */
    public function testGet_by_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::get_id
     * @todo   Implement testGet_id().
     */
    public function testGet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::get_email
     * @todo   Implement testGet_email().
     */
    public function testGet_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::check_password
     * @todo   Implement testCheck_password().
     */
    public function testCheck_password() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::set_email
     * @todo   Implement testSet_email().
     */
    public function testSet_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::set_password
     * @todo   Implement testSet_password().
     */
    public function testSet_password() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::get_blacklist
     * @todo   Implement testGet_blacklist().
     */
    public function testGet_blacklist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::add_to_blacklist
     * @todo   Implement testAdd_to_blacklist().
     */
    public function testAdd_to_blacklist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers User::rm_from_blacklist
     * @todo   Implement testRm_from_blacklist().
     */
    public function testRm_from_blacklist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
